//
//  SSTStyleKit.h
//  FullScreen
//
//  Created by FullScreen on 5/25/14.
//  Copyright (c) 2014 FullScreen. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface SSTStyleKit : NSObject

// Drawing Methods
+ (void)drawTopBarBackgroundImage;

@end
