//
//  SSTStyleKit.m
//  FullScreen
//
//  Created by FullScreen on 5/25/14.
//  Copyright (c) 2014 FullScreen. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "SSTStyleKit.h"


@implementation SSTStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawTopBarBackgroundImage;
{

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 320, 44)];
    [UIColor.clearColor setFill];
    [rectanglePath fill];
}

@end
