//
//  SSTStyleKit.h
//  FullScreen
//
//  Created by FullScreen on 5/26/14.
//  Copyright (c) 2014 FullScreen. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@class PCGradient;

@interface SSTStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* clearTopBarBackgroundImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* blueTopBarBackgroundImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* topShadowTargets;

// Colors
+ (UIColor*)myBlueColor;
+ (UIColor*)myShadowGradientClearColor;
+ (UIColor*)myShadowGradientBlackColor;

// Gradients
+ (PCGradient*)myShadowGradient;

// Drawing Methods
+ (void)drawClearTopBarBackgroundImage;
+ (void)drawBlueTopBarBackgroundImage;
+ (void)drawTopShadow;

// Generated Images
+ (UIImage*)imageOfClearTopBarBackgroundImage;
+ (UIImage*)imageOfBlueTopBarBackgroundImage;
+ (UIImage*)imageOfTopShadow;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end
